image: gradle:latest

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME


cache:
  paths:
    - .m2/repository/
    - target/

stages:
  - buildnew 
  - result

deploy:
  stage: buildnew
  image: registry.gitlab.com/cloudtron/example-java-service/utils-src:2
  variables:
    ACTION: env
  script:
    - env
    - test

runscript:
  stage: result
  image:  registry.hub.docker.com/library/groovy:3.0.12-jdk17
  script:
    - groovy src/script/utils.groovy