image: gradle:latest

variables:
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode"

cache:
  paths:
    - .m2/repository/
    - target/

build:
  stage: build
  script:
    - ./gradlew clean build 

test:
  stage: test
  script:
    - ./gradlew clean test

deploy:
  stage: deploy
  script:
    - echo deploy
  only:
    - master
