image: gradle:latest

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME


cache:
  paths:
    - .m2/repository/
    - target/

stages:
  - test
  - visualize
  - deploy 

# build:
#   stage: build
#   script:
#     - ./gradlew clean build 

test:
  stage: test
  script:
    - ./gradlew clean test jacocoTestReport
  artifacts:
    when: always
    reports:
      junit: build/test-results/test/**/TEST-*.xml

deploy:
  stage: deploy
  script:
    - echo deploy
  only:
    - master

