image: gradle:latest

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - GRADLE_USER_HOME="$(pwd)/.gradle"
  - export GRADLE_USER_HOME


cache:
  paths:
    - .m2/repository/
    - target/

stages:
  - buildnew 

deploy:
  stage: buildnew
  image: registry.gitlab.com/cloudtron/example-java-service/utils-src:2
  script:
    - env

